### ISSUE TITLE
Groupe 1 - Historique conflits 

### ISSUE THREAD

**Issue by Ahmedthedev** [julien-sarazin/learning-nodejs#2]
Bonjour,

Nous avons rencontré un léger problème de compréhension sur votre sujet.

Il est dis qu'il faut être authentifier pour lister les produits vendus.
=> "Permettre de consulter un historique des produits qui ont été vendu sur la plateforme"

Mais plus loin, vous précisez, que seul les admins ont cette possibilité.
=> "La consultation de l'historique des produits vendu sur la plateformes ne pourra être fait que par un membre de G-Bay."

Nous aimerons une précision sur ce point, s'il s'agit uniquement des admins ou tous les users authentifier.

Merci

**Comment by julien-sarazin** [comment]
Il s'agit bien uniquement des administrateurs de GBay.
