### ISSUE TITLE
Quelques précisions

### ISSUE THREAD

**Issue by CarolineChaudey** [julien-sarazin/learning-nodejs#3]
Bonjour, suite à l'analyse du sujet nous aurions quelques questions :

- on parle d'édition des informations personnelles et de d'ajout de crédits sans qu'ils soient listés dans les services, j'imagine qu'ils en sont tout de même ?
- peut-il y avoir des catégories imbriquées ?
- un produit peut-il appartenir à plusieurs catégories ?
- une note concerne-t-elle le vendeur ou le produit qu'il a vendu (étant donné qu'on ne peut en laisser une qu'après achat ou obtention)? Si elle concerne le vendeur, peut-on considérer qu'une note fait partie d'un avis ? Y a-t-il des contraintes pour laisser un avis ?

**Comment by julien-sarazin** [comment]
- Ces fonctionnalités font effectivement parties des services. Je viens d'editer le README en conséquence.
- Si par catégories imbriquées vous parlez de relations **N-N** entre catégories la réponse est **non**.
- Oui un produit peut appartenir à plusieurs catégories
- Elle concerne les deux, une note est attribuée par rapport à une vente, l'avis lui, concerne uniquement le vendeur et doit être unique par utilisateur. Un même utilisateur ne doit pas être capable de donner deux avis sur un même vendeur. J'ai également édité le README en ce sens.

**Comment by CarolineChaudey** [comment]
- Pour les catégories je pensais plutôt à une relation 1-N. Par exemple les catégories iPhone et Mac qui sont dans la catégorie Apple.

**Comment by julien-sarazin** [comment]
Ce n'est pas nécessaire. Tout comme la relation N-N. Vous pouvez la mettre en place si vous le souhaitez mais cela reste facultatif.

**Comment by CarolineChaudey** [comment]
D'accord merci beaucoup.
