### ISSUE TITLE
Concept de l'enchère

### ISSUE THREAD

**Issue by CarolineChaudey** [julien-sarazin/learning-nodejs#4]
Bonjour,

Par rapport au déroulement des enchères, est-ce que la fin de l'enchère est, comme dans la vie réelle, déterminée par un délai après la dernière meilleure offre (le fameux "une fois, deux fois, 3 fois"), ou la durée de l'enchère est-elle déterminée depuis le départ (par le vendeur par exemple) ?

**Comment by julien-sarazin** [comment]
Lors d'une mise aux encheres un produit dispose d'un prix initial et d'une duree maximum d'encheres. Passé ce delai, la plus grosse enchere remporte le produit.
