### ISSUE TITLE
noSQL vs SQL

### ISSUE THREAD

**Issue by CarolineChaudey** [julien-sarazin/learning-nodejs#5]
Comment savoir dans quel cas il est judicieux d'utiliser l'un ou l'autre ?

**Comment by julien-sarazin** [comment]
Tout depend du degree relationnel de votre modélisation. Si votre model est fortement relationnel (réseau social, statistiques, leaderboards) il convient d'utiliser une base de données relationnelle type SQL. Si au contraire vos modèles sont faiblement corrélés, penchez plus pour une utilisation NOSQL.

Enfin, il est possible d'avoir une utilisation des deux sur un meme projet. Un article intéressant d'un architecte logiciel réputé traite de ce sujet qu'il nomme Polyglot Persitence: https://martinfowler.com/bliki/PolyglotPersistence.html

Cordialement,

Société ASAPPS
Julien Sarazin | Président
A : 3B Rue Taylor, 75010 Paris
T : +33652473917
